# Generated by Django 5.1.1 on 2024-10-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='started_at',
        ),
    ]
